### ISSUE TITLE
Doesn't work with recent beta

### ISSUE THREAD

**Issue by dkadioglu** [audoban/PlayBar2#10]
Hi,

since yesterday there is a new beta (http://repository.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.13.111.g6bd0deca_amd64.deb) which brings back DBUS/MPRIS2. But PlayBar2 doesn't recognize Spotify running. Could you please have a look into that?
The same applies to PlayBar.

Thanks!

**Comment by audoban** [comment]
Ok, I will make track.

Thanks you

**Comment by audoban** [comment]
It thinks it's a bug in plasma5 ( mpris2 DataEngine ) or Spotify.

**Comment by dkadioglu** [comment]
Sorry, forgot to inform you about this one: https://community.spotify.com/t5/Help-Desktop-Linux-Windows-Web/Linux-Spotify-DBus-MPRIS2-support-not-fully-working/td-p/1208249

From my perspective only the Spotify devs can fix that. Maybe you can comment there and emphasize that your nice addon doesn't work with Spotify until they fix that (just an idea).

Sorry for the noise.

**Comment by dkadioglu** [comment]
This is fixed now! Spotify 1.0.28 works again as it should.
