### ISSUE TITLE
Settings window not opened on Arch Linux

### ISSUE THREAD

**Issue by varlesh** [audoban/PlayBar2#12]
Install version from AUR.
KDE 5.4.1
LOG (plasmashell):
http://pastebin.com/mpL91TKd

**Comment by dkadioglu** [comment]
I can confirm that. Still no settings window, even with 2.3.

**Comment by audoban** [comment]
Ok, I will review it, and I'll fix as quickly as possible

**Comment by audoban** [comment]
Try this please, on the terminal:
Install **plasmaengineexplorer**
* $ plasmaengineexplorer --engine playbar --source Provider # This is the engine that is responsible for settings.
 *  you right click on Provider and click "Get associated service".

*  operation: ShowSettings
*  Click to button "Start operation"
Please paste the log  here, and tell me what happens.
![instantanea1](https://cloud.githubusercontent.com/assets/7884292/11620246/0bbf18f6-9c7f-11e5-9eac-823de8e2ab0f.png)

**Comment by dkadioglu** [comment]
Thanks for your fast reaction! I think I found the problem:
First the respective dataengine wasn't even listed in the plasmaengineexplorer. I looked into the package which I used to install Playbar2 (https://aur.archlinux.org/packages/kdeplasma-applets-playbar2/) and found out that the file plasma_engine_playbar.so is installed to /usr/lib/qt5/plugins/plasma/dataengine/ whereas all the other dataengines reside in /usr/lib/qt/plugins/plasma/dataengine/. After copying the dataengine file there, the settings window is shown and works as it should. Do you have an idea how I or the package maintainer could fix that?

**Comment by audoban** [comment]
Try with this experimetal version.
https://github.com/audoban/PlayBar2/blob/CustomColors/dist/PKGBUILD

**Comment by dkadioglu** [comment]
The experimental works as it should and the dataengine gets installed to the right place. The necessary change seems to be in CMakeLists.txt in the commit https://github.com/audoban/PlayBar2/commit/45f749cbb9b101da38b1c857e01336e1a96dceb3. Do you want to propose that to the maintainer of the PKGBUILD in AUR or should I do that?

Thanks for your fast fix!

**Comment by audoban** [comment]
You do me a favor because I do not use ArchLinux. https://github.com/audoban/PlayBar2/commit/ae450f06f12f302a3de1fd2d18ed9027520728f8 :+1: 
Gracias por su dedicación.

**Comment by dkadioglu** [comment]
FYI The maintainer has patched the PKGBUILD in AUR.

**Comment by audoban** [comment]
Thank's :+1:
