### ISSUE TITLE
Please fix "Play/Pause" DeadBeef action

### ISSUE THREAD

**Issue by varlesh** [audoban/PlayBar2#13]
Plugin:
https://github.com/Serranya/deadbeef-mpris2-plugin.
If press "pause/play" button on Playbar2 - player set Pause.
But if press again "pause/play" button - not nothing :(
LOG:
plasma.engine.mpris2: Trying to perform the action "Play"
PS: Original mediacontrol widget KDE not have this problem, play/pause working.

**Comment by audoban** [comment]
This is a bug of the plugin https://github.com/Serranya/deadbeef-mpris2-plugin/commit/3646fa9608fe0d9796ad215abb0d2c76a82a38a2
