### ISSUE TITLE
Gentoo ebuild für your releases

### ISSUE THREAD

**Issue by tillschaefer** [audoban/PlayBar2#15]
Hi, 
i like your plasmoid a lot (much better than the default media widget), but did not want to pollute my system with an unmanaged installation, so i have created a small ebuild (Gentoo Package file) for PlayBar2. 

If you like, you can add this to your releases, or provide it at kde-look. By simply renaming the file to the desired version number, you can adjust the ebuild to new releases. 

filename: `playbar-2.3.ebuild`
```
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6
inherit cmake-utils

DESCRIPTION="Client MPRIS2, allows you to control your favorite media player"
HOMEPAGE="https://github.com/audoban/PlayBar2"
SRC_URI="https://github.com/audoban/PlayBar2/archive/v${PV}.tar.gz"

LICENSE="GPLv3"
SLOT="0"

KEYWORDS="~alpha ~amd64 ~arm ~hppa ~ia64 ~ppc ~ppc64 ~s390 ~sh ~sparc ~x86"

DEPEND="kde-frameworks/kglobalaccel
        kde-plasma/plasma-workspace
        kde-frameworks/kdeclarative
        kde-frameworks/kconfigwidgets
        kde-frameworks/kxmlgui
        kde-frameworks/kwindowsystem
        kde-frameworks/kdoctools"

S="${WORKDIR}/PlayBar2-${PV}"
```

**Comment by audoban** [comment]
Thank's for your contribution

**Comment by audoban** [comment]
Added https://github.com/audoban/PlayBar2/commit/c3b7a344460646afe65cd10fc7cb22bde591f3ae

**Comment by tillschaefer** [comment]
:-)
