### ISSUE TITLE
Picture Scaling

### ISSUE THREAD

**Issue by tillschaefer** [audoban/PlayBar2#16]
Hi, 
first of all, thanks for the great widget. I would like to propose an enhancement for it: I like to see the album cover really large :-), but it does not scale with the widget. If automatic scaling is problematic an option to adjust the size in the settings would also work out for me. 

I have attached two screenshots. The first one shows the widget in small. It looks nice in this setting. For the larger setting (screenshot2) however, the picture could use all the additional space. The skip and volume bar can stay vertically at the same position as before. 

![screenshot_20160614_222921](https://cloud.githubusercontent.com/assets/3009428/16058623/a160ec2c-327f-11e6-8585-e25deb18c014.png)
![screenshot_20160614_223005](https://cloud.githubusercontent.com/assets/3009428/16058622/a15559e8-327f-11e6-9e30-5af593a2b2d7.png)

**Comment by audoban** [comment]
__Hi,__
This is a little hard because I don't know what is the best layout for when widget is growing, but I will experiment with new layouts.
Any concept will be a great contribution.

**Comment by tillschaefer** [comment]
the scaling is always a bit problematic. e.g. the standard media widget for kde also has problems with scaling. 
I think there are three possible configurations regarding the aspect ratio:

1. height is much larger than width
2. a balanced height and width 
3. the width is much larger than the height

here are some mockups for these settings: 
![high](https://cloud.githubusercontent.com/assets/3009428/16231056/b1ad4fcc-37c4-11e6-8798-161c7b006f6d.png)

![balanced](https://cloud.githubusercontent.com/assets/3009428/16231063/b604e09e-37c4-11e6-978f-b6b9b806ebfe.png)
- This is maybe the most difficult configuration: It must reserve some space for the text and the controls, but should make the album art as large as possible without violating this constraint.

![wide](https://cloud.githubusercontent.com/assets/3009428/16231069/bd496f3c-37c4-11e6-9715-4a5490fb8c86.png)

**Comment by tillschaefer** [comment]
Here are the pencil sources (if you want to modify the mockups): https://github.com/tillschaefer/playbar2mockups

**Comment by audoban** [comment]
Thank's for your mockups, now I know how program this feature.

**Comment by droserasprout** [comment]
@audoban take a look at my fork. It's pretty ugly (layout breaks in some conditions) but do it's work for me. Thanks for your work, it's cool that Playbar will be more flexible soon.

**Comment by audoban** [comment]
Already I seen your fork. It is curious that has removed the title bar, you don't like?

@tillschaefer @droserasprout, Look at the new layout

![screenshot_20160702_011552](https://cloud.githubusercontent.com/assets/7884292/16538735/bae477d8-3ff2-11e6-9b0a-7648f96fbb67.png)

**Comment by droserasprout** [comment]
@audoban there's no many situations in which more than one MPRIS2 player is needed at the same time. Anyway in this case you can always use context menu, it's not so common action to worth design failure, imho. Adding clickable player icon somewhere under the cover art may be a compromise option (imho, again).

**Comment by tillschaefer** [comment]
Looks great so far! How about smaller borders for/around the picture?

**Comment by audoban** [comment]
Hi, @tillschaefer it will fix

**Comment by audoban** [comment]
I experimented with a few things regarding the proposal @droserasprout, but do not know what is the best solution.
Should I remove the button in the title bar 
![plasmoid](https://cloud.githubusercontent.com/assets/7884292/16605585/ea3e071e-42f5-11e6-8798-af3016fea4c2.png)
or the title bar?
![plasmoid-without-titlebar](https://cloud.githubusercontent.com/assets/7884292/16605646/83bcc3b2-42f6-11e6-89aa-ebd4ecee1d8e.png)

@tillschaefer, @droserasprout  What do you think?

**Comment by tillschaefer** [comment]
the second solution looks amazingly modern!
