### ISSUE TITLE
Black background nocover on Clementine

### ISSUE THREAD

**Issue by varlesh** [audoban/PlayBar2#18]
Nocover image have black background, but original icon is have transparent background.
Preview:
![image](https://cloud.githubusercontent.com/assets/8083855/19769710/321e87b6-9c65-11e6-8f50-974bfb5b2a2b.png)
On Plasma notification icon show normaly and on Clementine too:
![image](https://cloud.githubusercontent.com/assets/8083855/19769742/5ad04f96-9c65-11e6-8675-98c031da5330.png)
Original icon:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme-kde/blob/master/papirus/64x64/places/nocover.svg

**Comment by audoban** [comment]
It seems that clementine renders poorly the SVG covers delivered in the MPRIS2 engine.

_Temporal cover art generated from clementine_
![clementine-art-nx4102](https://cloud.githubusercontent.com/assets/7884292/26757832/0d47ee14-4890-11e7-8064-f187606bacde.jpg)

A quick fix might be not to use SVG for the cover art

**Comment by droserasprout** [comment]
Fixed!
https://github.com/clementine-player/Clementine/pull/5886

**Comment by audoban** [comment]
@droserasprout  Cool :)
