### ISSUE TITLE
Bigger icons size on panel

### ISSUE THREAD

**Issue by varlesh** [audoban/PlayBar2#19]
For KDE now default icon size 22px it's contained for status (on icon theme) and Plasma desktop theme.
Used icon **media**, but icons on Playbar bigger and blurred.
Please see screenshots for compare:
Original icon on Plasma theme:
![image](https://cloud.githubusercontent.com/assets/8083855/20663428/7fe85ef6-b568-11e6-813f-d9659b7e061e.png)
Icons on panel:
![image](https://cloud.githubusercontent.com/assets/8083855/20663562/047a863a-b569-11e6-9319-f3681730a473.png)
Option **toolbar** not solve this, because icons not use 22px and very tiny (and blurred too):
![image](https://cloud.githubusercontent.com/assets/8083855/20663710/883f6b7a-b569-11e6-93e0-b8702f86cf09.png)

**Comment by audoban** [comment]
Thanks for the report, and sorry for my delay. I have some vacations and I want to continue with the devel

**Comment by audoban** [comment]
That's the Papirus icon theme?

**Comment by audoban** [comment]
Hello again what do you think about this?
![spectacle kn1403](https://cloud.githubusercontent.com/assets/7884292/26750557/d19a928a-47eb-11e7-8f67-0770ed6a4608.png)

**Comment by audoban** [comment]
And with the stop control.

![spectacle ns9958](https://cloud.githubusercontent.com/assets/7884292/26750583/6e9059e4-47ec-11e7-98cf-24a95161003d.png)

**Comment by audoban** [comment]
![spectacle x11263](https://cloud.githubusercontent.com/assets/7884292/26757548/0be14daa-4885-11e7-9689-f856c4d5ba10.png)

The blurred effect it was fixed.
