### ISSUE TITLE
Support for KF 5.12

### ISSUE THREAD

**Issue by KottV** [audoban/PlayBar2#2]
Greetings!
With new release of KF 12 the PlayBar stopped to work :(

>LANG=C DEBUG=yes plasmawindowed audoban.applet.playbar
>unversioned plugin detected, may result in instability
>kf5.kservice.sycoca: Trying to open ksycoca from "/home/kv/.cache/ksycoca5"
>Falling back to legacy separed QQmlEngine for applet "org.kde.desktopcontainment"
>unversioned plugin detected, may result in instability
>requesting config for "PlayBar" without a containment!
>"file:///usr/share/plasma/plasmoids/audoban.applet.playbar/contents/ui/main.qml" 
> "Error loading QML file.
>"
>couldn't create slave: "Unable to create io-slave:
>klauncher said: ??????????? ???????? ?plasmapackage?.

Last string is "Сообщение klauncher: Неизвестный протокол «plasmapackage»." Smth like "Unknouwn protocol "plasmapackage""

**Comment by audoban** [comment]
Issue confirmed and fixed.
all imports than to "plasmapackage:/" have been changed by the standard syntax QML http://doc.qt.io/qt-5/qtqml-syntax-imports.html

https://github.com/audoban/PlayBar2/commit/255fe5d11d99db6b859163b4711ae6c1daa3029d
Thanks a lot. :+1:
