### ISSUE TITLE
[Feature request] Launchers for recent media players

### ISSUE THREAD

**Issue by vmorenomarin** [audoban/PlayBar2#20]
Add a launcher for default music player when it is not opened.

Excellent widget. Great work!!

**Comment by audoban** [comment]
I agree, thanks for your Idea

**Comment by audoban** [comment]
In KDE there is no such thing as "Default Player", then I can't get this information from environment.

It is to make the applet remember the last 3 players, something as "Recent players".
Do you agree?

**Comment by vmorenomarin** [comment]
I am agree!!

**Comment by audoban** [comment]
__Most recent player(Amarok in this case)__
Furthermore If the user press left click, the most recent player should be opened
![spectacle x23575](https://cloud.githubusercontent.com/assets/7884292/26757452/37fd60b2-4881-11e7-89e8-2979dca49359.png)

**Contextual menu without music players opened** 
![spectacle m24576](https://cloud.githubusercontent.com/assets/7884292/26757456/4909191e-4881-11e7-9cdd-502a12f4eed9.png)

**Comment by vmorenomarin** [comment]
Yes, just like that!! Thanks a lot.
