### ISSUE TITLE
[Feature request] Easy acces to change multimedia source

### ISSUE THREAD

**Issue by vmorenomarin** [audoban/PlayBar2#23]
Could be interesting easy access icons to change the multimedia source, like in the next mockup:

![playbar](https://cloud.githubusercontent.com/assets/13444664/26737616/8536699c-4790-11e7-9703-bf46ba45310a.png)
There are two icons next to the Settings icon. This icons enable the fast change between the multimedia sources. In this example, between Clementine or VLC.

**Comment by audoban** [comment]
I am agree with your purpose of improve the access to multimedia sources, but on the new version the Bar of title was removed.

![spectacle t19993](https://cloud.githubusercontent.com/assets/7884292/26749921/49b6a98a-47dc-11e7-80d8-0d9f088d7ea1.png)

Do you have another purpose? I really can not think of anything

**Comment by f1u77y** [comment]
I'd suggest to return the player title (and make just like the OP proposed) but make it hidden by default and show it on some action (click in the top?).

**Comment by audoban** [comment]
I really like it as it looks without the title bar. Maybe I can add a combobox into cover.

**Comment by audoban** [comment]
Implemented in newfeatures branch.

![spectacle ns2699](https://user-images.githubusercontent.com/7884292/32480421-cbf0fbd4-c35c-11e7-9aca-432a0dfa5022.png)

**Comment by vmorenomarin** [comment]
It works perfectly. Thank you for considering the recommendation.

**Comment by audoban** [comment]
I'm still making some improvements, I'll upload them soon.
