### ISSUE TITLE
Not possible in systray anymore

### ISSUE THREAD

**Issue by kupiqu** [audoban/PlayBar2#24]
Is it not possible to have PlayBar in the systray anymore? 
I really liked that feature, to replace Plasma's default media player control... Would it be possible to get it back?

**Comment by kupiqu** [comment]
In particular I like that PlayBar, if in systray, is only present when needed, that is when players are running :)

**Comment by audoban** [comment]
Disable it for this version, because it was very problematic and it did not look very good.
However I wish to add the feature again, but with a better Layout and a behavior.

**Comment by kupiqu** [comment]
Previous version was working great in my system. 

The only issue I experienced was that keyboard shortcuts stopped working when in addition to the playbar applet in the systray (via latte-dock), I added another one to the desktop (via plasma).

Looking forward to your new implementation of this feature, I'm sure it will be awesome! (do you have a tentative time plan for it?)

**Comment by audoban** [comment]
Now I'm working on LatteDock, then I think that I can added the feature for the Tuesday and the Wednesday I will launch a small release.

> The only issue I experienced was that keyboard shortcuts stopped working when in addition to the playbar applet in the systray (via latte-dock), I added another one to the desktop (via plasma).

This a curious issue, and is obvious because in such case the instance that manage the global shortcuts is duplicated, then occur a conflict in the actions.

**Comment by audoban** [comment]
@kupiqu The placement in systemtray was enabled, tell me what you think?

**Comment by kupiqu** [comment]
I got a warning while running cmake:

CMake Warning at /usr/lib/x86_64-linux-gnu/cmake/KF5Package/KF5PackageMacros.cmake:58 (message):
  warnings during generation of metainfo for audoban.applet.playbar.systray:
PlayBar2/plasmoid-systray/../plasmoid-systray
  has enabled «NoDisplay»

not sure if this is important or not...

**Comment by audoban** [comment]
Please, ignore it, such property is totally necessary for avoid the entries duplicates of PlayBar on widget explorer.

**Comment by kupiqu** [comment]
It works great!

Perhaps the only thing is that it would be nice that settings that do not apply in systemtray appear greyed out (with a bonus of a tooltip explaining why, perhaps?)

**Comment by audoban** [comment]
> Perhaps the only thing is that it would be nice that settings that do not apply in systemtray appear greyed out (with a bonus of a tooltip explaining why, perhaps?)

I'll keep it in mind.
