### ISSUE TITLE
new icon too small?

### ISSUE THREAD

**Issue by kupiqu** [audoban/PlayBar2#25]
New icon of PlayBar seems to be very small in my system. Is there a way to make it bigger?

![image](https://cloud.githubusercontent.com/assets/3875196/26760537/304f7f0e-48e9-11e7-9ed8-e70c56508c79.png)

**Comment by audoban** [comment]
Wow, How bad does that look xD. I will fix it today.

**Comment by wintericie** [comment]
The icons looks really small. I don't know if it is related to the HiDPI setting in my desktop (Scale=2).
![screenshot_20170605_141253](https://cloud.githubusercontent.com/assets/5930472/26772699/a9acce22-49f9-11e7-96f9-efdecb88c8cc.png)

**Comment by audoban** [comment]
mm, I wanted to avoid the blurred effect and the issue https://github.com/audoban/PlayBar2/issues/19, the large icons then I decided use just a icon size, however my mistake was not take account the scale of the monitor. 

Maybe I can take as note the size the icons in the systray.

**Comment by audoban** [comment]
Tell me what you think now?

**Comment by kupiqu** [comment]
Mmm, it's weird. I added the applet and looked ok, but then I restarted latte and it looks sort of tiny again:

![image](https://cloud.githubusercontent.com/assets/3875196/26802549/d7369cdc-4a0e-11e7-9b7f-93bde4c91f22.png)

**Comment by kupiqu** [comment]
wait! if I use icon layout, it looks fine :)

![image](https://cloud.githubusercontent.com/assets/3875196/26802672/63c224c8-4a0f-11e7-9adb-62661dc04019.png)

**Comment by audoban** [comment]
> Mmm, it's weird. I added the applet and looked ok, but then I restarted latte and it looks sort of tiny again:

Ok I already uploaded a small fix, now when there are not sources the icon restores your max size

**Comment by kupiqu** [comment]
Awesome!
