### ISSUE TITLE
Vertical layout does not persist

### ISSUE THREAD

**Issue by vmorenomarin** [audoban/PlayBar2#27]
In the last update I liked so much the vertical layout. I did configure my play bar widget in vertical mode, but when I turn on my pc, this layout does not persist. Then, I go to the settings of the widget: the vertical layout appears chosen. So, I have to chose horizontal layout and then go back to the vertical to apply the changes to get this mode.

**Comment by audoban** [comment]
Fixed, please test the last commit and tell me if works fine.

**Comment by vmorenomarin** [comment]
Yes, fixed. Thanks.
