### ISSUE TITLE
[Feature Reguest] - Improve margins for Play/Pause layout

### ISSUE THREAD

**Issue by psifidotos** [audoban/PlayBar2#28]
it would nice to have a little smaller margins in the right side of the Play/Pause layout. Playbar can not be added yet in the systray but it is possible to add it next to it.... Like the screenshot shows the only thing that distinguish the playbar applet from the systray items is a bigger margin on the right side. If this margin was changed a bit then the playbar applet would look like as it belonged in the systray when no media is playing...

![image](https://user-images.githubusercontent.com/2216474/27003409-a52bcae8-4dfe-11e7-983b-58ff0c7d2da3.png)

**Comment by audoban** [comment]
@psifidotos In the version master is possible add PlayBar to systray.

> Like the screenshot shows the only thing that distinguish the playbar applet from the systray items is a bigger margin on the right side.

You're right. I will to fix
