### ISSUE TITLE
Incorrect work on openSUSE 42.2

### ISSUE THREAD

**Issue by IkiruOG** [audoban/PlayBar2#29]
QObject::connect: Cannot connect (null)::settingsChanged(QString) to PlayBar::loadSettings()
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)
qml: plugin name audoban.applet.playbar

**Comment by audoban** [comment]
> QObject::connect: Cannot connect (null)::settingsChanged(QString) to PlayBar::loadSettings()

Fixed in master.
