### ISSUE TITLE
Can't compile Playbar2 on Kubuntu (Ubuntu) 15.04 with KDE5 and Plasma2

### ISSUE THREAD

**Issue by MurzNN** [audoban/PlayBar2#3]
I have install plasma-framework-devel and plasma5-workspace-devel packages (seems that it have other names in Ubuntu - plasma-workspace-dev and plasma-framework-dev).

But after this I see the errors on compiling Playbar2:
```
$ cmake -DCMAKE_INSTALL_PREFIX=/usr ..    
CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:77 (find_package):
  Could not find a package configuration file provided by "KF5DocTools"
  (requested version 5.9.0) with any of the following names:

    KF5DocToolsConfig.cmake
    kf5doctools-config.cmake

  Add the installation prefix of "KF5DocTools" to CMAKE_PREFIX_PATH or set
  "KF5DocTools_DIR" to a directory containing one of the above files.  If
  "KF5DocTools" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)


-- Could NOT find KF5DocTools: found neither KF5DocToolsConfig.cmake nor kf5doctools-config.cmake 
CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:77 (find_package):
  Could not find a package configuration file provided by "KF5Declarative"
  (requested version 5.9.0) with any of the following names:

    KF5DeclarativeConfig.cmake
    kf5declarative-config.cmake

  Add the installation prefix of "KF5Declarative" to CMAKE_PREFIX_PATH or set
  "KF5Declarative_DIR" to a directory containing one of the above files.  If
  "KF5Declarative" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)


-- Could NOT find KF5Declarative: found neither KF5DeclarativeConfig.cmake nor kf5declarative-config.cmake 
CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:77 (find_package):
  Could not find a package configuration file provided by "KF5WindowSystem"
  (requested version 5.9.0) with any of the following names:

    KF5WindowSystemConfig.cmake
    kf5windowsystem-config.cmake

  Add the installation prefix of "KF5WindowSystem" to CMAKE_PREFIX_PATH or
  set "KF5WindowSystem_DIR" to a directory containing one of the above files.
  If "KF5WindowSystem" provides a separate development package or SDK, be
  sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)


-- Could NOT find KF5WindowSystem: found neither KF5WindowSystemConfig.cmake nor kf5windowsystem-config.cmake 
CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:77 (find_package):
  Could not find a package configuration file provided by "KF5ConfigWidgets"
  (requested version 5.9.0) with any of the following names:

    KF5ConfigWidgetsConfig.cmake
    kf5configwidgets-config.cmake

  Add the installation prefix of "KF5ConfigWidgets" to CMAKE_PREFIX_PATH or
  set "KF5ConfigWidgets_DIR" to a directory containing one of the above
  files.  If "KF5ConfigWidgets" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)


-- Could NOT find KF5ConfigWidgets: found neither KF5ConfigWidgetsConfig.cmake nor kf5configwidgets-config.cmake 
CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:77 (find_package):
  Could not find a package configuration file provided by "KF5XmlGui"
  (requested version 5.9.0) with any of the following names:

    KF5XmlGuiConfig.cmake
    kf5xmlgui-config.cmake

  Add the installation prefix of "KF5XmlGui" to CMAKE_PREFIX_PATH or set
  "KF5XmlGui_DIR" to a directory containing one of the above files.  If
  "KF5XmlGui" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)


-- Could NOT find KF5XmlGui: found neither KF5XmlGuiConfig.cmake nor kf5xmlgui-config.cmake 
CMake Warning at /usr/share/ECM/find-modules/FindKF5.cmake:77 (find_package):
  Could not find a package configuration file provided by "KF5GlobalAccel"
  (requested version 5.9.0) with any of the following names:

    KF5GlobalAccelConfig.cmake
    kf5globalaccel-config.cmake

  Add the installation prefix of "KF5GlobalAccel" to CMAKE_PREFIX_PATH or set
  "KF5GlobalAccel_DIR" to a directory containing one of the above files.  If
  "KF5GlobalAccel" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:14 (find_package)


-- Could NOT find KF5GlobalAccel: found neither KF5GlobalAccelConfig.cmake nor kf5globalaccel-config.cmake 
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find KF5 (missing: DocTools Declarative WindowSystem
  ConfigWidgets XmlGui GlobalAccel) (found suitable version "5.9.0", minimum
  required is "5.9.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:113 (find_package_handle_standard_args)
  CMakeLists.txt:14 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/murz/temp/2015-07/PlayBar2-master/build/CMakeFiles/CMakeOutput.log".
```
Maybe I need to install some additional packages? Which names of packages can I try to install?

**Comment by audoban** [comment]
Yes!, you need install some packages. I am currently using OpenSUSE 13.2/Plasma5 then I don't know exactly the name of them in Ubuntu.
Look for these packages:
`kdeclarative-devel`
`kglobalaccel-devel`
`kconfigwidgets-devel`
`kxmlgui-devel`
`kwindowsystem-devel`
`kdoctools-devel`
`extra-cmake-modules` *need for build*

**Comment by varlesh** [comment]
```
[ 41%] Building CXX object engine/CMakeFiles/plasma_engine_playbar.dir/configdialog.cpp.o
In file included from /home/kubuntu/Downloads/PlayBar2-master/engine/configdialog.cpp:27:0:
/home/kubuntu/Downloads/PlayBar2-master/engine/playbarsettings.h:7:20: fatal error: kdebug.h: No such file or directory
 #include <kdebug.h>
                    ^
compilation terminated.
engine/CMakeFiles/plasma_engine_playbar.dir/build.make:67: recipe for target 'engine/CMakeFiles/plasma_engine_playbar.dir/configdialog.cpp.o' failed
make[2]: *** [engine/CMakeFiles/plasma_engine_playbar.dir/configdialog.cpp.o] Error 1
CMakeFiles/Makefile2:107: recipe for target 'engine/CMakeFiles/plasma_engine_playbar.dir/all' failed
make[1]: *** [engine/CMakeFiles/plasma_engine_playbar.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
What package for kdebug.h?

**Comment by varlesh** [comment]
Solved, install kdelibs5-dev. Playbar building and working.

**Comment by varlesh** [comment]
I create packages for kubuntu 15.04. Maybe it's useful to someone:
http://mykubik.blogspot.ru/2015/07/playbar-2-kde-5.html

**Comment by MurzNN** [comment]
Thanks to @varlesh  here is package dependencies for build PlayBar2 on Ubuntu/Kubuntu:
```
sudo apt-get install g++ plasma-framework-dev plasma-workspace-dev libkf5declarative-dev libkf5globalaccel-dev libkf5configwidgets-dev libkf5xmlgui-dev libkf5windowsystem-dev kdoctools-dev cmake extra-cmake-modules kdelibs5-dev
```
Please merge fork with commit https://github.com/varlesh/PlayBar2/commit/ae89974b40d8138124e041d7b499154bc9f7889a

And here https://launchpad.net/~murznn/+archive/ubuntu/playbar2 is my try to create PPA repository with packages for Ubuntu.

**Comment by varlesh** [comment]
Packages for Vivid:
https://launchpad.net/~varlesh-l/+archive/ubuntu/plasma5-tools

**Comment by roberthchan** [comment]
I had the same problem even with the libraries mentioned, using opensuse 13.2
searching i found https://github.com/haraldF/homebrew-kf5/issues/28
And installing "ki18n-devel 5.13.0-81.2" Works im Plasma: 5.3.95-98.4.

**Comment by roberthchan** [comment]
Im instaled Leap OpenSUSE and output:
[ 56%] Built target pofiles_1                                                                                                                                           
[ 56%] Built target pofiles_2                                                                                                                                           
[ 56%] Built target pofiles_3                                                                                                                                           
[ 56%] Built target pofiles_4                                                                                                                                           
[ 56%] Built target pofiles_5                                                                                                                                           
[ 56%] Automatic moc for target plasma_engine_playbar                                                                                                                   
[ 56%] Built target plasma_engine_playbar_automoc                                                                                                                       
[ 56%] Building CXX object engine/CMakeFiles/plasma_engine_playbar.dir/configdialog.cpp.o                                                                               
In file included from /home/roberth/Descargas/PlayBar2-master/engine/configdialog.cpp:27:0:                                                                             
/home/roberth/Descargas/PlayBar2-master/engine/playbarsettings.h:7:20: fatal error: kdebug.h: No existe el fichero o el directorio                                      
 #include <kdebug.h>                                                                                                                                                    
                    ^                                                                                                                                                   
compilation terminated.                                                                                                                                                 
engine/CMakeFiles/plasma_engine_playbar.dir/build.make:74: recipe for target 'engine/CMakeFiles/plasma_engine_playbar.dir/configdialog.cpp.o' failed                    
make[2]: *** [engine/CMakeFiles/plasma_engine_playbar.dir/configdialog.cpp.o] Error 1                                                                                   
CMakeFiles/Makefile2:339: recipe for target 'engine/CMakeFiles/plasma_engine_playbar.dir/all' failed                                                                    
make[1]: *** [engine/CMakeFiles/plasma_engine_playbar.dir/all] Error 2                                                                                                  
Makefile:138: recipe for target 'all' failed                                                                                                                            
make: *** [all] Error 2

**Comment by audoban** [comment]
Ok @roberthchan I will fix

**Comment by roberthchan** [comment]
Thank you @audoban Works!

**Comment by audoban** [comment]
@roberthchan Fixed
