### ISSUE TITLE
keyboard shortcuts to move back and forward

### ISSUE THREAD

**Issue by kupiqu** [audoban/PlayBar2#34]
Playbar is very powerful, which now applies also to online multimedia players in common browsers like chromium and firefox via plasma-browser-integration. This is great to control pause/play, for instance.

There is however sth in online players that annoys me quite a bit, and playbar could perhaps help quite a lot: it is not easy to move the player position back and forward in a controlled manner. Instead, one needs to drag and drop the dot of the current player position, which is a very coarse way to do it.

It would be awesome to have the possibility to move back and forward the position of online multimedia players via Playbar. Ideally with an option in settings to set how many seconds to jump (so a user can configure it to her preference), and with keyboard shortcuts to activate the jump in each direction.

Do you think this is something doable?

**Comment by audoban** [comment]
@kupiqu yes is totally posible. 
Do you suggest some shorcut?

**Comment by kupiqu** [comment]
Great!

Wrt to keyboard shortcuts, I don't know, perhaps a combination of either ctrl, meta or shift, on the one hand, and the left/right arrows on the other, would be nice :)

**Comment by audoban** [comment]
Please test the branch https://github.com/audoban/PlayBar2/tree/forward-backward-globalshorcut

**Comment by kupiqu** [comment]
Wow, it works so great!!

I tested it in online players using Chromium-browser and locally in dragonplayer. 

The only issue I've seen is that it doesn't work properly in SMPlayer, but I don't think it's related to Playbar, since it's working fine in other players, so it must be a problem of SMPlayer (perhaps because of the chosen shortcut ?). I'm using alt+ctrl+arrows because other combinations interfered with already taken shortcuts.

This is not that important as I can use SMPlayer shortcuts as well, although they only work when the application is under focus.

**Comment by audoban** [comment]
@kupiqu 
Then I suggest change the default key sequence to Ctrl + Media Next, it is more comfortable.
> I'm using alt+ctrl+arrows because other combinations interfered with already taken shortcuts.

Yes is a problem with the Mpris2 interface of SMPlayer
> The only issue I've seen is that it doesn't work properly in SMPlayer

**Comment by kupiqu** [comment]
I have changed the shortcuts to meta+arrows, as they interfered with kwin features that I don't use. This is very comfortable now, and in fact I use meta+space for play/pause combo, so they all now fit together.

Indeed, the shortcut change didn't fix the problem with SMPlayer. I was going to say that I will have to start using mpv directly, but it's not detected so I assume it doesn't support Mpris...

**Comment by audoban** [comment]
@KOT040188  Do you have any other suggestions or can we close this thread?

**Comment by audoban** [comment]
this is a SMPlayer bug. It does not work for me either
> Indeed, the shortcut change didn't fix the problem with SMPlayer. I was going to say that I will have to start using mpv directly, but it's not detected so I assume it doesn't support Mpris...

**Comment by kupiqu** [comment]
I guess you refer to me. Yes, we can close the issue, thank you very much!

**Comment by kupiqu** [comment]
Will you port the feature to master soon? :)

**Comment by audoban** [comment]
Yes, but I need to fix the issue #35

**Comment by kupiqu** [comment]
> this is a SMPlayer bug. It does not work for me either

FYI: this is now fixed in current stable version of SMPlayer :)

**Comment by kupiqu** [comment]
I guess it's an issue of MPRIS2 but for the case it's not (or perhaps you can confirm it really is):

When I use the new shortcuts to move the player back and forth, a lot of times I see that the position of reference gets stacked, not where the player currently is but in a previous position.

I have seen this strange behavior in online players as well as in Dragon/SMPlayer.

Could you please try to reproduce? Thanks!

**Comment by audoban** [comment]
It's strange, I'll see what happens.

**Comment by kupiqu** [comment]
Thanks!
