### ISSUE TITLE
Notification error

### ISSUE THREAD

**Issue by varlesh** [audoban/PlayBar2#9]
Notification with mouse area show this:
![screen13](https://cloud.githubusercontent.com/assets/8083855/9575552/5374cc1a-4fd9-11e5-8005-86aaa44dc3bc.png)
version 2.2
Kubuntu 15.04
KDE 5.3.2

**Comment by audoban** [comment]
Confirmed and Fixed. https://github.com/audoban/PlayBar2/commit/ec0baa6b24290d12f482c15d26f618045034c15f
